% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 3: Data Exploration},
  pdfauthor={Camila Zarate Ospina},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Assignment 3: Data Exploration}
\author{Camila Zarate Ospina}
\date{}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
Data Exploration.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Salk\_A03\_DataExploration.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on \textless\textgreater.

\hypertarget{set-up-your-r-session}{%
\subsection{Set up your R session}\label{set-up-your-r-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Check your working directory, load necessary packages (tidyverse), and
  upload two datasets: the ECOTOX neonicotinoid dataset
  (ECOTOX\_Neonicotinoids\_Insects\_raw.csv) and the Niwot Ridge NEON
  dataset for litter and woody debris
  (NEON\_NIWO\_Litter\_massdata\_2018-08\_raw.csv). Name these datasets
  ``Neonics'' and ``Litter'', respectively.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/camilazarate/OneDrive - Duke University/2 Second semester/Data analytics/Environmental_Data_Analytics_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"/Users/camilazarate/OneDrive - Duke University/2 Second semester/Data analytics/Environmental_Data_Analytics_2021"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages -------------------------------------------------------------------------------------------- tidyverse 1.3.0 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.5.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ----------------------------------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Neonics <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/ECOTOX_Neonicotinoids_Insects_raw.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{Litter <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/NEON_NIWO_Litter_massdata_2018-08_raw.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{learn-about-your-system}{%
\subsection{Learn about your system}\label{learn-about-your-system}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  The neonicotinoid dataset was collected from the Environmental
  Protection Agency's ECOTOX Knowledgebase, a database for ecotoxicology
  research. Neonicotinoids are a class of insecticides used widely in
  agriculture. The dataset that has been pulled includes all studies
  published on insects. Why might we be interested in the ecotoxicologoy
  of neonicotinoids on insects? Feel free to do a brief internet search
  if you feel you need more background information.
\end{enumerate}

\begin{quote}
Answer: Neonicotinoids insecticide is linked to adverse effects in
nature, including negative impacts on bee's colonies and other
polinators. Some bird populations have decrease as a consequence of the
use of Neonicotinoid, which erradicated all the insects they eat. As a
consequence, this insecticide has been restricted in european countries
and a few states in the US. Ecotoxicology is the science that studies
the effects of toxic chemicals - like Neonicotinoids - on biological
organisms at the organisms, community, ecosystem and biosphere level.
One might be interested in the ecotoxicologoy of neonicotinoids on
insects because in the long run, negative effects on insects can
translate into reduced polinators, directly affecting our food systems.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  The Niwot Ridge litter and woody debris dataset was collected from the
  National Ecological Observatory Network, which collectively includes
  81 aquatic and terrestrial sites across 20 ecoclimatic domains. 32 of
  these sites sample forest litter and woody debris, and we will focus
  on the Niwot Ridge long-term ecological research (LTER) station in
  Colorado. Why might we be interested in studying litter and woody
  debris that falls to the ground in forests? Feel free to do a brief
  internet search if you feel you need more background information.
\end{enumerate}

\begin{quote}
Answer: Woody debris plays an important role in carbon budgets and
nutrient cycles and provides habitat for terrestrial and aquatic
organisms. Likewise, litter plays a role by transferring nutrients from
the aboveground biomass to the soil and in general improving soil
quality. Together, they can give us great information regarding the
health of the forest and potential disruptions of nutrient cycles.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  How is litter and woody debris sampled as part of the NEON network?
  Read the NEON\_Litterfall\_UserGuide.pdf document to learn more. List
  three pieces of salient information about the sampling methods here:
\end{enumerate}

\begin{quote}
Answer: * Random sampling. Litter and woody debris are sampled at
terrestrial NEON sites. The sampling process occurs in tower plots whose
location is randomly selected. Depending on the site of the forest
(low-statured vegetation, forested, low-statue) tower plots are placed
at specific distance from each other. * Depending on the vegetation (\%
aerial cover of woody vegetation and height), trap placement within
plots may be either targeted or randomized. * Sampling frequency also
depends on the vegetation: Ground traps - once per year, elevated traps
in deciduous forest - once every two weeks, elevated traps at evergreen
sites - once every 1-2 months.
\end{quote}

\hypertarget{obtain-basic-summaries-of-your-data-neonics}{%
\subsection{Obtain basic summaries of your data
(Neonics)}\label{obtain-basic-summaries-of-your-data-neonics}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  What are the dimensions of the dataset?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(Neonics) }\CommentTok{# row column}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4623   30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(Litter)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 188  19
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Using the \texttt{summary} function on the ``Effects'' column,
  determine the most common effects that are studied. Why might these
  effects specifically be of interest?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Option 1: Create and object and change the Effect column from string to factor so the function summary works. }
\CommentTok{# Effect <- as.factor(Neonics$Effect)}
\CommentTok{# Effect}
\CommentTok{# summary(Effect)}

\CommentTok{# Option 2: Add the clause stringsAsFactors = TRUE when reading the csv and use summary. }
\KeywordTok{summary}\NormalTok{(Neonics}\OperatorTok{$}\NormalTok{Effect)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Accumulation        Avoidance         Behavior     Biochemistry 
##               12              102              360               11 
##          Cell(s)      Development        Enzyme(s) Feeding behavior 
##                9              136               62              255 
##         Genetics           Growth        Histology       Hormone(s) 
##               82               38                5                1 
##    Immunological     Intoxication       Morphology        Mortality 
##               16               12               22             1493 
##       Physiology       Population     Reproduction 
##                7             1803              197
\end{verbatim}

\begin{quote}
Answer: Effects are defined as a response that directly results from the
action of a chemical stressor. Mortality and population are the two most
common effects. This is of interest because high mortality rates and
lower population of insects might affect the food chain that depends on
the insects, ultimately affecting other insects, mammals and birds.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Using the \texttt{summary} function, determine the six most commonly
  studied species in the dataset (common name). What do these species
  have in common, and why might they be of interest over other insects?
  Feel free to do a brief internet search for more information if
  needed.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Neonics}\OperatorTok{$}\NormalTok{Species.Common.Name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          Honey Bee                     Parasitic Wasp 
##                                667                                285 
##              Buff Tailed Bumblebee                Carniolan Honey Bee 
##                                183                                152 
##                         Bumble Bee                   Italian Honeybee 
##                                140                                113 
##                    Japanese Beetle                  Asian Lady Beetle 
##                                 94                                 76 
##                     Euonymus Scale                           Wireworm 
##                                 75                                 69 
##                  European Dark Bee                  Minute Pirate Bug 
##                                 66                                 62 
##               Asian Citrus Psyllid                      Parastic Wasp 
##                                 60                                 58 
##             Colorado Potato Beetle                    Parasitoid Wasp 
##                                 57                                 51 
##                Erythrina Gall Wasp                       Beetle Order 
##                                 49                                 47 
##        Snout Beetle Family, Weevil           Sevenspotted Lady Beetle 
##                                 47                                 46 
##                     True Bug Order              Buff-tailed Bumblebee 
##                                 45                                 39 
##                       Aphid Family                     Cabbage Looper 
##                                 38                                 38 
##               Sweetpotato Whitefly                      Braconid Wasp 
##                                 37                                 33 
##                       Cotton Aphid                     Predatory Mite 
##                                 33                                 33 
##             Ladybird Beetle Family                         Parasitoid 
##                                 30                                 30 
##                      Scarab Beetle                      Spring Tiphia 
##                                 29                                 29 
##                        Thrip Order               Ground Beetle Family 
##                                 29                                 27 
##                 Rove Beetle Family                      Tobacco Aphid 
##                                 27                                 27 
##                       Chalcid Wasp             Convergent Lady Beetle 
##                                 25                                 25 
##                      Stingless Bee                  Spider/Mite Class 
##                                 25                                 24 
##                Tobacco Flea Beetle                   Citrus Leafminer 
##                                 24                                 23 
##                    Ladybird Beetle                          Mason Bee 
##                                 23                                 22 
##                           Mosquito                      Argentine Ant 
##                                 22                                 21 
##                             Beetle         Flatheaded Appletree Borer 
##                                 21                                 20 
##               Horned Oak Gall Wasp                 Leaf Beetle Family 
##                                 20                                 20 
##                  Potato Leafhopper         Tooth-necked Fungus Beetle 
##                                 20                                 20 
##                       Codling Moth          Black-spotted Lady Beetle 
##                                 19                                 18 
##                       Calico Scale                Fairyfly Parasitoid 
##                                 18                                 18 
##                        Lady Beetle             Minute Parasitic Wasps 
##                                 18                                 18 
##                          Mirid Bug                   Mulberry Pyralid 
##                                 18                                 18 
##                           Silkworm                     Vedalia Beetle 
##                                 18                                 18 
##              Araneoid Spider Order                          Bee Order 
##                                 17                                 17 
##                     Egg Parasitoid                       Insect Class 
##                                 17                                 17 
##           Moth And Butterfly Order       Oystershell Scale Parasitoid 
##                                 17                                 17 
## Hemlock Woolly Adelgid Lady Beetle              Hemlock Wooly Adelgid 
##                                 16                                 16 
##                               Mite                        Onion Thrip 
##                                 16                                 16 
##              Western Flower Thrips                       Corn Earworm 
##                                 15                                 14 
##                  Green Peach Aphid                          House Fly 
##                                 14                                 14 
##                          Ox Beetle                 Red Scale Parasite 
##                                 14                                 14 
##                 Spined Soldier Bug              Armoured Scale Family 
##                                 14                                 13 
##                   Diamondback Moth                      Eulophid Wasp 
##                                 13                                 13 
##                  Monarch Butterfly                      Predatory Bug 
##                                 13                                 13 
##              Yellow Fever Mosquito                Braconid Parasitoid 
##                                 13                                 12 
##                       Common Thrip       Eastern Subterranean Termite 
##                                 12                                 12 
##                             Jassid                         Mite Order 
##                                 12                                 12 
##                          Pea Aphid                   Pond Wolf Spider 
##                                 12                                 12 
##           Spotless Ladybird Beetle             Glasshouse Potato Wasp 
##                                 11                                 10 
##                           Lacewing            Southern House Mosquito 
##                                 10                                 10 
##            Two Spotted Lady Beetle                         Ant Family 
##                                 10                                  9 
##                       Apple Maggot                            (Other) 
##                                  9                                670
\end{verbatim}

\begin{quote}
Answer: Honey Bee (667), Parasitic Wasp (285), Buff Tailed Bumblebee
(183), Carniolan Honey Bee (152), Bumble Bee (140), Italian Honeybee
(113). They all have in common that they're all bees, which might be of
special interest since bees are one of the most important polinators,
thereby playing an esential role in food systems.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Concentrations are always a numeric value. What is the class of
  Conc.1..Author. in the dataset, and why is it not numeric?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(Neonics}\OperatorTok{$}\NormalTok{Conc.}\DecValTok{1}\NormalTok{..Author.)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{quote}
Answer: Some rows have symbols like / or \textasciitilde.
\end{quote}

\hypertarget{explore-your-data-graphically-neonics}{%
\subsection{Explore your data graphically
(Neonics)}\label{explore-your-data-graphically-neonics}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Using \texttt{geom\_freqpoly}, generate a plot of the number of
  studies conducted by publication year.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_freqpoly}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Publication.Year), }\DataTypeTok{bins =} \DecValTok{30}\NormalTok{, }\DataTypeTok{color =} \StringTok{"darkgreen"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Number of studies by publication year"}\NormalTok{, }\DataTypeTok{x =} \StringTok{"Publication year"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/geom_freqpoly-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Reproduce the same graph but now add a color aesthetic so that
  different Test.Location are displayed as different colors.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_freqpoly}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Publication.Year, }\DataTypeTok{color =}\NormalTok{ Test.Location), }\DataTypeTok{bins =} \DecValTok{30}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Number of studies by publication year by test location"}\NormalTok{, }\DataTypeTok{x =} \StringTok{"Publication year"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-6-1.pdf}

Interpret this graph. What are the most common test locations, and do
they differ over time?

\begin{quote}
Answer: The most common test locations are Lab and Field natural.
Overall, the location Field natural has had a steady number of studies
conducted around 100 studies, except for the year 2010 where it had a
peack of around 370 studies. On the contrary, Lab has seen a progressive
increase of number of studies over the years, reaching a peak of 650
studies in 2015.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Create a bar graph of Endpoint counts. What are the two most common
  end points, and how are they defined? Consult the ECOTOX\_CodeAppendix
  for more information.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Neonics, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ Endpoint)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"darkblue"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{ )) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=} \StringTok{"Endpoint counts"}\NormalTok{, }\DataTypeTok{x =} \StringTok{"Endpoint ID"}\NormalTok{, }\DataTypeTok{y =} \StringTok{"Count"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{quote}
Answer: The most common two endpoits are NOEL
(No-observable-effect-level) and LOEL (Lowest-observable-effect-level).
\end{quote}

\hypertarget{explore-your-data-litter}{%
\subsection{Explore your data (Litter)}\label{explore-your-data-litter}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Determine the class of collectDate. Is it a date? If not, change to a
  date and confirm the new class of the variable. Using the
  \texttt{unique} function, determine which dates litter was sampled in
  August 2018.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{class}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{collectDate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Litter}\OperatorTok{$}\NormalTok{collectDate <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{collectDate, }\DataTypeTok{format =} \StringTok{"%Y-%m-%d"}\NormalTok{) }
\KeywordTok{class}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{collectDate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{August2018Samples <-}\StringTok{ }\KeywordTok{unique}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{collectDate)}
\NormalTok{August2018Samples}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2018-08-02" "2018-08-30"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Using the \texttt{unique} function, determine how many plots were
  sampled at Niwot Ridge. How is the information obtained from
  \texttt{unique} different from that obtained from \texttt{summary}?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PlotsSampled <-}\StringTok{ }\KeywordTok{unique}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{plotID)}
\NormalTok{PlotsSampled}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "NIWO_061" "NIWO_064" "NIWO_067" "NIWO_040" "NIWO_041" "NIWO_063"
##  [7] "NIWO_047" "NIWO_051" "NIWO_058" "NIWO_046" "NIWO_062" "NIWO_057"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(PlotsSampled)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Plots_Sampled <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(Litter}\OperatorTok{$}\NormalTok{plotID)}
\KeywordTok{summary}\NormalTok{(PlotsSampled)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Length     Class      Mode 
##        12 character character
\end{verbatim}

\begin{quote}
Answer: The information obtained from Unique are all of the different
objects/names/categories in a column. If the objects are repeated,
unique won't show the repetitions. Summary gives information on object's
characteristics like lenght and class.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Create a bar graph of functionalGroup counts. This shows you what type
  of litter is collected at the Niwot Ridge sites. Notice that litter
  types are fairly equally distributed across the Niwot Ridge sites.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{fill =} \StringTok{"purple4"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{20}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{ )) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{"Functional group counts"}\NormalTok{, }\DataTypeTok{x=}\StringTok{"Functional group"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Using \texttt{geom\_boxplot} and \texttt{geom\_violin}, create a
  boxplot and a violin plot of dryMass by functionalGroup.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup, }\DataTypeTok{y =}\NormalTok{ dryMass)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{20}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{ )) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{"Dry mass by functional group"}\NormalTok{, }\DataTypeTok{x=}\StringTok{"Functional group"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Dry mass"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A03_DataExploration_files/figure-latex/boxplot-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Litter) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_violin}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ functionalGroup, }\DataTypeTok{y =}\NormalTok{ dryMass), }
              \DataTypeTok{draw_quantiles =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.25}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.75}\NormalTok{)) }\OperatorTok{+}
\StringTok{   }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{20}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{ )) }\OperatorTok{+}
\StringTok{   }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{"Dry mass by functional group"}\NormalTok{, }\DataTypeTok{x=}\StringTok{"Functional group"}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Dry mass"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
## collapsing to unique 'x' values

## Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
## collapsing to unique 'x' values

## Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
## collapsing to unique 'x' values
\end{verbatim}

\includegraphics{A03_DataExploration_files/figure-latex/violin-1.pdf}

Why is the boxplot a more effective visualization option than the violin
plot in this case?

\begin{quote}
Answer: The boxplot shows summary statistics of the data, and the violin
plot shows the distribution of the data. In this case, the violin plot
doesn't show a good visualization because the data is extremely skewed.
\end{quote}

What type(s) of litter tend to have the highest biomass at these sites?

\begin{quote}
Answer: Needles, followed by twings/branches.
\end{quote}

\end{document}
