% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 4: Data Wrangling},
  pdfauthor={Camila Zarate Ospina},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Assignment 4: Data Wrangling}
\author{Camila Zarate Ospina}
\date{}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
Data Wrangling

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Fay\_A04\_DataWrangling.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, Feb 16 @ 11:59pm.

\hypertarget{set-up-your-session}{%
\subsection{Set up your session}\label{set-up-your-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Check your working directory, load the \texttt{tidyverse} and
  \texttt{lubridate} packages, and upload all four raw data files
  associated with the EPA Air dataset. See the README file for the EPA
  air datasets for more information (especially if you have not worked
  with air quality data previously).
\item
  Explore the dimensions, column names, and structure of the datasets.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\OperatorTok{::}\NormalTok{opts_chunk}\OperatorTok{$}\KeywordTok{set}\NormalTok{(}\DataTypeTok{echo =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{tidy.opts =} \KeywordTok{list}\NormalTok{(}\DataTypeTok{width.cutoff=}\DecValTok{80}\NormalTok{),}
                      \DataTypeTok{tidy =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#1 Working directory, libraries, reading the datasets. }
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/camilazarate/OneDrive - Duke University/2 Second semester/Data analytics/Environmental_Data_Analytics_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{setwd}\NormalTok{(}\StringTok{"/Users/camilazarate/OneDrive - Duke University/2 Second semester/Data analytics/Environmental_Data_Analytics_2021"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(lubridate)}

\NormalTok{PM25_NC2019 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/EPAair_PM25_NC2018_raw.csv"}\NormalTok{,}
                        \DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{PM25_NC2018 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/EPAair_PM25_NC2019_raw.csv"}\NormalTok{,}
                        \DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}

\NormalTok{O3_NC2018 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/EPAair_O3_NC2018_raw.csv"}\NormalTok{,}
                      \DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{O3_NC2019 <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/EPAair_O3_NC2019_raw.csv"}\NormalTok{,}
                      \DataTypeTok{stringsAsFactors =} \OtherTok{TRUE}\NormalTok{)}

\CommentTok{#2 Dimensions of datasets.}
\KeywordTok{colnames}\NormalTok{(PM25_NC2018)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Date"                           "Source"                        
##  [3] "Site.ID"                        "POC"                           
##  [5] "Daily.Mean.PM2.5.Concentration" "UNITS"                         
##  [7] "DAILY_AQI_VALUE"                "Site.Name"                     
##  [9] "DAILY_OBS_COUNT"                "PERCENT_COMPLETE"              
## [11] "AQS_PARAMETER_CODE"             "AQS_PARAMETER_DESC"            
## [13] "CBSA_CODE"                      "CBSA_NAME"                     
## [15] "STATE_CODE"                     "STATE"                         
## [17] "COUNTY_CODE"                    "COUNTY"                        
## [19] "SITE_LATITUDE"                  "SITE_LONGITUDE"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(PM25_NC2018)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8581   20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{colnames}\NormalTok{(PM25_NC2019)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Date"                           "Source"                        
##  [3] "Site.ID"                        "POC"                           
##  [5] "Daily.Mean.PM2.5.Concentration" "UNITS"                         
##  [7] "DAILY_AQI_VALUE"                "Site.Name"                     
##  [9] "DAILY_OBS_COUNT"                "PERCENT_COMPLETE"              
## [11] "AQS_PARAMETER_CODE"             "AQS_PARAMETER_DESC"            
## [13] "CBSA_CODE"                      "CBSA_NAME"                     
## [15] "STATE_CODE"                     "STATE"                         
## [17] "COUNTY_CODE"                    "COUNTY"                        
## [19] "SITE_LATITUDE"                  "SITE_LONGITUDE"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(PM25_NC2019)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8983   20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{colnames}\NormalTok{(O3_NC2018)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Date"                                
##  [2] "Source"                              
##  [3] "Site.ID"                             
##  [4] "POC"                                 
##  [5] "Daily.Max.8.hour.Ozone.Concentration"
##  [6] "UNITS"                               
##  [7] "DAILY_AQI_VALUE"                     
##  [8] "Site.Name"                           
##  [9] "DAILY_OBS_COUNT"                     
## [10] "PERCENT_COMPLETE"                    
## [11] "AQS_PARAMETER_CODE"                  
## [12] "AQS_PARAMETER_DESC"                  
## [13] "CBSA_CODE"                           
## [14] "CBSA_NAME"                           
## [15] "STATE_CODE"                          
## [16] "STATE"                               
## [17] "COUNTY_CODE"                         
## [18] "COUNTY"                              
## [19] "SITE_LATITUDE"                       
## [20] "SITE_LONGITUDE"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(O3_NC2018)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9737   20
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{colnames}\NormalTok{(O3_NC2019)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Date"                                
##  [2] "Source"                              
##  [3] "Site.ID"                             
##  [4] "POC"                                 
##  [5] "Daily.Max.8.hour.Ozone.Concentration"
##  [6] "UNITS"                               
##  [7] "DAILY_AQI_VALUE"                     
##  [8] "Site.Name"                           
##  [9] "DAILY_OBS_COUNT"                     
## [10] "PERCENT_COMPLETE"                    
## [11] "AQS_PARAMETER_CODE"                  
## [12] "AQS_PARAMETER_DESC"                  
## [13] "CBSA_CODE"                           
## [14] "CBSA_NAME"                           
## [15] "STATE_CODE"                          
## [16] "STATE"                               
## [17] "COUNTY_CODE"                         
## [18] "COUNTY"                              
## [19] "SITE_LATITUDE"                       
## [20] "SITE_LONGITUDE"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(O3_NC2019)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10592    20
\end{verbatim}

\hypertarget{wrangle-individual-datasets-to-create-processed-files.}{%
\subsection{Wrangle individual datasets to create processed
files.}\label{wrangle-individual-datasets-to-create-processed-files.}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Change date to date
\item
  Select the following columns: Date, DAILY\_AQI\_VALUE, Site.Name,
  AQS\_PARAMETER\_DESC, COUNTY, SITE\_LATITUDE, SITE\_LONGITUDE
\item
  For the PM2.5 datasets, fill all cells in AQS\_PARAMETER\_DESC with
  ``PM2.5'' (all cells in this column should be identical).
\item
  Save all four processed datasets in the Processed folder. Use the same
  file names as the raw files but replace ``raw'' with ``processed''.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3 Change the dates to Date format. }
\KeywordTok{class}\NormalTok{(PM25_NC2018}\OperatorTok{$}\NormalTok{Date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PM25_NC2018}\OperatorTok{$}\NormalTok{Date <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(PM25_NC2018}\OperatorTok{$}\NormalTok{Date, }\DataTypeTok{format =} \StringTok{"%m/%d/%Y"}\NormalTok{) }

\KeywordTok{class}\NormalTok{(PM25_NC2019}\OperatorTok{$}\NormalTok{Date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PM25_NC2019}\OperatorTok{$}\NormalTok{Date <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(PM25_NC2019}\OperatorTok{$}\NormalTok{Date, }\DataTypeTok{format =} \StringTok{"%m/%d/%Y"}\NormalTok{) }

\KeywordTok{class}\NormalTok{(O3_NC2018}\OperatorTok{$}\NormalTok{Date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{O3_NC2018}\OperatorTok{$}\NormalTok{Date <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(O3_NC2018}\OperatorTok{$}\NormalTok{Date, }\DataTypeTok{format =} \StringTok{"%m/%d/%Y"}\NormalTok{) }

\KeywordTok{class}\NormalTok{(O3_NC2019}\OperatorTok{$}\NormalTok{Date)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{O3_NC2019}\OperatorTok{$}\NormalTok{Date <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(O3_NC2019}\OperatorTok{$}\NormalTok{Date, }\DataTypeTok{format =} \StringTok{"%m/%d/%Y"}\NormalTok{) }

\CommentTok{#4 Select columns}
\NormalTok{PM25_NC2018_select <-}\StringTok{ }\KeywordTok{select}\NormalTok{(PM25_NC2018, Date, DAILY_AQI_VALUE,}
\NormalTok{                             Site.Name, AQS_PARAMETER_DESC, COUNTY,}
\NormalTok{                             SITE_LATITUDE, SITE_LONGITUDE)}

\NormalTok{PM25_NC2019_select <-}\StringTok{ }\KeywordTok{select}\NormalTok{(PM25_NC2019, Date, DAILY_AQI_VALUE,}
\NormalTok{                             Site.Name, AQS_PARAMETER_DESC, COUNTY,}
\NormalTok{                             SITE_LATITUDE, SITE_LONGITUDE)}

\NormalTok{O3_NC2018_select <-}\StringTok{ }\KeywordTok{select}\NormalTok{(O3_NC2018, Date, DAILY_AQI_VALUE,}
\NormalTok{                           Site.Name, AQS_PARAMETER_DESC, COUNTY,}
\NormalTok{                           SITE_LATITUDE, SITE_LONGITUDE)}

\NormalTok{O3_NC2019_select <-}\StringTok{ }\KeywordTok{select}\NormalTok{(O3_NC2019, Date, DAILY_AQI_VALUE,}
\NormalTok{                           Site.Name, AQS_PARAMETER_DESC, COUNTY,}
\NormalTok{                           SITE_LATITUDE, SITE_LONGITUDE)}

\CommentTok{#5 Write PM2.5 in AQS_PARAMETER_DES}
\NormalTok{PM25_NC2018_select <-}\StringTok{ }\KeywordTok{mutate}\NormalTok{(PM25_NC2018_select, }\DataTypeTok{AQS_PARAMETER_DESC =} \StringTok{"PM2.5"}\NormalTok{)}
\NormalTok{PM25_NC2019_select <-}\StringTok{ }\KeywordTok{mutate}\NormalTok{(PM25_NC2019_select, }\DataTypeTok{AQS_PARAMETER_DESC =} \StringTok{"PM2.5"}\NormalTok{)}

\CommentTok{#6 Save processed datasets }
\KeywordTok{write.csv}\NormalTok{(PM25_NC2018_select, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{file =}
            \StringTok{"./Data/Processed/EPAair_PM25_NC2018_processed.csv"}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(PM25_NC2019_select, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{file =}
            \StringTok{"./Data/Processed/EPAair_PM25_NC2019_processed.csv"}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(O3_NC2018_select, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{file =}
            \StringTok{"./Data/Processed/EPAair_O3_NC2018_processed.csv"}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(O3_NC2019_select, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{file =}
            \StringTok{"./Data/Processed/EPAair_O3_NC2019_processed.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{combine-datasets}{%
\subsection{Combine datasets}\label{combine-datasets}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Combine the four datasets with \texttt{rbind}. Make sure your column
  names are identical prior to running this code.
\item
  Wrangle your new dataset with a pipe function (\%\textgreater\%) so
  that it fills the following conditions:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Include all sites that the four data frames have in common: ``Linville
  Falls'', ``Durham Armory'', ``Leggett'', ``Hattie Avenue'', ``Clemmons
  Middle'', ``Mendenhall School'', ``Frying Pan Mountain'', ``West
  Johnston Co.'', ``Garinger High School'', ``Castle Hayne'', ``Pitt
  Agri. Center'', ``Bryson City'', ``Millbrook School'' (the function
  \texttt{intersect} can figure out common factor levels)
\item
  Some sites have multiple measurements per day. Use the
  split-apply-combine strategy to generate daily means: group by date,
  site, aqs parameter, and county. Take the mean of the AQI value,
  latitude, and longitude.
\item
  Add columns for ``Month'' and ``Year'' by parsing your ``Date'' column
  (hint: \texttt{lubridate} package)
\item
  Hint: the dimensions of this dataset should be 14,752 x 9.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Spread your datasets such that AQI values for ozone and PM2.5 are in
  separate columns. Each location on a specific date should now occupy
  only one row.
\item
  Call up the dimensions of your new tidy dataset.
\item
  Save your processed dataset with the following file name:
  ``EPAair\_O3\_PM25\_NC1718\_Processed.csv''
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#7 Combine datasets }
\CommentTok{# Read processed datasets }
\CommentTok{#PM25_2018 <- read.csv("./Data/Processed/EPAair_PM25_NC2018_processed.csv", stringsAsFactors = TRUE)}
\CommentTok{#PM25_2019 <- read.csv("./Data/Processed/EPAair_PM25_NC2019_processed.csv", stringsAsFactors = TRUE)}
\CommentTok{#O3_2018 <- read.csv("./Data/Processed/EPAair_O3_NC2018_processed.csv", stringsAsFactors = TRUE)}
\CommentTok{#O3_2019 <- read.csv("./Data/Processed/EPAair_O3_NC2019_processed.csv", stringsAsFactors = TRUE)}
\CommentTok{# Combine datasets}
\NormalTok{EPA_Air <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(PM25_NC2018_select, PM25_NC2019_select, O3_NC2018_select, O3_NC2019_select)}

\CommentTok{#8 Wrangle dataset}
\NormalTok{EPA_Air_Processed <-}\StringTok{ }\NormalTok{EPA_Air }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(Site.Name }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Linville Falls"}\NormalTok{, }\StringTok{"Durham Armory"}\NormalTok{, }\StringTok{"Leggett"}\NormalTok{,}
                          \StringTok{"Hattie Avenue"}\NormalTok{, }\StringTok{"Clemmons Middle"}\NormalTok{,}
                          \StringTok{"Mendenhall School"}\NormalTok{, }\StringTok{"Frying Pan Mountain"}\NormalTok{,}
                          \StringTok{"West Johnston Co."}\NormalTok{, }\StringTok{"Garinger High School"}\NormalTok{,}
                          \StringTok{"Castle Hayne"}\NormalTok{, }\StringTok{"Pitt Agri. Center"}\NormalTok{, }\StringTok{"Bryson City"}\NormalTok{,}
                          \StringTok{"Millbrook School"}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Date, Site.Name, AQS_PARAMETER_DESC, COUNTY) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{meanAQI =} \KeywordTok{mean}\NormalTok{ (DAILY_AQI_VALUE), }
            \DataTypeTok{meanLatitude =} \KeywordTok{mean}\NormalTok{(SITE_LATITUDE),}
            \DataTypeTok{meanLongitud =} \KeywordTok{mean}\NormalTok{(SITE_LONGITUDE)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{month =} \KeywordTok{month}\NormalTok{(Date)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{year =} \KeywordTok{year}\NormalTok{(Date))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` regrouping output by 'Date', 'Site.Name', 'AQS_PARAMETER_DESC' (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#9 Spread column that contains ozone and PM2.5 values.}
\CommentTok{# This generates 2 new columns }
\NormalTok{EPA_Air_spread <-}\StringTok{ }\KeywordTok{pivot_wider}\NormalTok{(EPA_Air_Processed, }\DataTypeTok{names_from =}\NormalTok{ AQS_PARAMETER_DESC,}
                              \DataTypeTok{values_from =}\NormalTok{ meanAQI)}

\CommentTok{#10}
\KeywordTok{colnames}\NormalTok{(EPA_Air_spread)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"         "Site.Name"    "COUNTY"       "meanLatitude" "meanLongitud"
## [6] "month"        "year"         "PM2.5"        "Ozone"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(EPA_Air_spread)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 8976    9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#11}
\KeywordTok{write.csv}\NormalTok{(EPA_Air_spread, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{file =}
            \StringTok{"EPAair_O3_PM25_NC1718_Processed.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{generate-summary-tables}{%
\subsection{Generate summary tables}\label{generate-summary-tables}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\item
  Use the split-apply-combine strategy to generate a summary data frame.
  Data should be grouped by site, month, and year. Generate the mean AQI
  values for ozone and PM2.5 for each group. Then, add a pipe to remove
  instances where a month and year are not available (use the function
  \texttt{drop\_na} in your pipe).
\item
  Call up the dimensions of the summary dataset.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# 12 Summaries}
\CommentTok{# Logic: Take data by site, month and year. Take the mean of all data from 1 site in a specific month in a specific year and calculate the mean. }

\CommentTok{# Summaries using drop_na}
\NormalTok{EPA_Air_summaries <-}\StringTok{ }\NormalTok{EPA_Air_spread }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Site.Name, month, year) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{meanIQ_Ozone =} \KeywordTok{mean}\NormalTok{(PM2}\FloatTok{.5}\NormalTok{), }
            \DataTypeTok{meanIQ_pm25 =} \KeywordTok{mean}\NormalTok{(Ozone)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{drop_na}\NormalTok{(month, year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` regrouping output by 'Site.Name', 'month' (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Summaries using na.omit}
\NormalTok{EPA_Air_summaries2 <-}\StringTok{ }\NormalTok{EPA_Air_spread }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Site.Name, month, year) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{meanIQ_Ozone =} \KeywordTok{mean}\NormalTok{(PM2}\FloatTok{.5}\NormalTok{), }
            \DataTypeTok{meanIQ_pm25 =} \KeywordTok{mean}\NormalTok{(Ozone)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{na.omit}\NormalTok{(month, year)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` regrouping output by 'Site.Name', 'month' (override with `.groups` argument)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#13 Dimensions}
\KeywordTok{dim}\NormalTok{(EPA_Air_summaries) }\CommentTok{#drop_na}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 308   5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(EPA_Air_summaries2) }\CommentTok{#na.omit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 101   5
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Why did we use the function \texttt{drop\_na} rather than
  \texttt{na.omit}?
\end{enumerate}

\begin{quote}
Answer: The function ``na.omit'' omits all the rows that contain NA's in
the dataset, instead of only focusing on the columns ``month'' and
``year''. The result is a table with no NA's at all and 101
observations. The ``drop\_na'' function only focusses on the columns
``month'' and ``year'', and since there are no NA's in those columns,
the resulting table keeps 308 observations. Since we only want to remove
NA's from the columns ``month'' and ``year'', we used ``drop\_na''.
\end{quote}

\end{document}
